export { default as Footer } from './footer/Footer'
export { default as Contact } from './contact/Contact'
export { default as Caracteristicas } from './caracteristicas/Caracteristicas'
export { default as Header } from './header/Header'
export { default as Modules } from './modules/Modules'
export { default as Principal } from './principal/Principal'
